server:
  port: 9090
spring:
  redis:
    host: 110.40.210.213
    port: 6379
    password: 956766
    database: 0
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://110.40.210.213:3306/blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: blog
      password: Bx377zJimRwSywyL
#  redis:
#      host: 110.40.210.213
#      port: 6379
#      password: YSY@20031018
#      timeout: 2000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #  # 设置MyBatis-Plus的全局配置
  #  global-config:
  #    db-config:
  #      # 设置实体类所对应的表的统一前缀
  #      table-prefix: t_
  #      # 设置统一的主键生成策略
  #      id-type: auto
  #  # 配置类型别名所对应的包
  type-aliases-package: com.blog.pojo
  #  # 扫描通用枚举的
  # 包
#  type-enums-package: com.interest.enums

blog:
  path: /Users/a1002/Downloads/blog/img/


